env_list = [
    { product = [
            {prefix = "3.", start = 13, stop = 14},
            {prefix = "pygame2.", start = 5, stop = 5},
    ] },
]

[env_run_base]
description = "run tests with pytest"
deps = [
    "pytest>=9",
    "pytest-cov",
    "pytest-sugar",
    { replace = "if", condition = "factor['pygame2.5']", then = ["pygame-ce>=2.5,<2.6"], extend = true },
]
commands = [["pytest", { replace = "posargs", extend = true }]]
